# Automates the github actions for webscraper

name: pupeteer job street Web Scraper Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs everyday
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Update apt and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-xcb1 libxcomposite1 libxi6 libxtst6 libnss3 libatk1.0-0 libcups2 libxrandr2 \
            liboss4-salsa-asound2 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libxdamage1 \
            libxss1 libgbm1 libpangoft2-1.0-0

      # Step 4: Install Python dependencies with specific versions
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r jobStreet_Scraper_requirement.txt 

      # Step 4: Install Chromium for pyppeteer
      - name: Install Chromium for pyppeteer
        run: |
          python -m pyppeteer.install

      # Step 5: Install Xvfb (for headless mode)
      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb

      - name: Run puppeteer Script
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &  # Start Xvfb in the background
          export DISPLAY=:99  # Set the DISPLAY variable
          python puppet_jobstreet.py 

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Stash any unstaged changes before pulling
      - name: Stash unstaged changes
        run: |
          git stash

      # Pull the latest changes from GitHub with rebase
      - name: Pull latest changes from GitHub
        run: |
          git pull origin main --rebase

      # Apply stashed changes
      - name: Apply stashed changes
        run: |
          git stash pop || echo "No changes to apply"
      
      # Commit and push the new data
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Scraped job street" || echo "No changes to commit"
          git push origin main
        env:
          # This GITHUB_TOKEN is automatically provided by GitHub Actions
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
